import {
  LifeAutomationRule,
  AutomationExecutionLog,
  GuildSyndicate,
  SyndicateLeaderboardEntry,
  BiometricReadinessMetric,
  WebhookIntegrationConfig,
} from '../types';

export const INITIAL_AUTOMATIONS: LifeAutomationRule[] = [
  {
    id: 'auto-1',
    title: 'High-Priority Task Boss Strike',
    description: 'Whenever a High-Priority task is completed, automatically deal 150 Critical DMG to the active Boss Raid.',
    enabled: true,
    category: 'execution',
    trigger: {
      type: 'task_completed',
      label: 'Task Completed',
    },
    condition: {
      field: 'priority',
      operator: 'equals',
      value: 'high',
      label: 'Priority is High',
    },
    action: {
      type: 'deal_boss_damage',
      label: 'Deal 150 DMG to Boss',
      value: 150,
    },
    runCount: 0,
    iconName: 'Swords',
  },
  {
    id: 'auto-2',
    title: 'Habit Mastery Shield Recovery',
    description: 'When any daily habit reaches a 7-day streak milestone, automatically grant 1 Streak Shield and 30 bonus XP.',
    enabled: true,
    category: 'discipline',
    trigger: {
      type: 'habit_streak_reached',
      label: 'Habit Streak Reached',
      params: { threshold: 7 },
    },
    action: {
      type: 'replenish_streak_shield',
      label: 'Replenish 1 Streak Shield',
      value: 1,
    },
    runCount: 0,
    iconName: 'ShieldCheck',
  },
  {
    id: 'auto-3',
    title: 'Trading Tilt Safeguard Protocol',
    description: 'If 2 consecutive losing trades are journaled in a single day, immediately lock live order execution and dispatch AI Coaching reflection.',
    enabled: true,
    category: 'trading',
    trigger: {
      type: 'trade_logged',
      label: 'Journaled Trade Saved',
    },
    condition: {
      field: 'pnl',
      operator: 'lte',
      value: 0,
      label: 'Loss Detected',
    },
    action: {
      type: 'trigger_ai_safeguard',
      label: 'Lock Terminal & Deploy Reflection Prompt',
      value: 'tilt_cooling_period',
    },
    runCount: 0,
    iconName: 'AlertTriangle',
  },
  {
    id: 'auto-4',
    title: 'Syllabus Quiz Perfection Bounty',
    description: 'When completing a Course Lab quiz with 100% score, automatically award +1 Skill Perk Point for talent tree specialization.',
    enabled: true,
    category: 'learning',
    trigger: {
      type: 'lesson_passed',
      label: 'Course Lab Passed',
    },
    condition: {
      field: 'score',
      operator: 'equals',
      value: 100,
      label: 'Perfect 100% Score',
    },
    action: {
      type: 'award_perk_points',
      label: 'Grant 1 Skill Perk Point',
      value: 1,
    },
    runCount: 0,
    iconName: 'Zap',
  },
  {
    id: 'auto-5',
    title: 'Biometric Prime Peak Multiplier',
    description: 'When morning sleep score exceeds 85% and HRV is optimal, activate 1.5x Focus XP Multiplier for the first 4 hours of the day.',
    enabled: true,
    category: 'health',
    trigger: {
      type: 'biometric_threshold',
      label: 'Wearable Sync Complete',
    },
    condition: {
      field: 'sleepScore',
      operator: 'gte',
      value: 85,
      label: 'Sleep Score >= 85%',
    },
    action: {
      type: 'grant_xp',
      label: 'Activate 1.5x Daily XP Buff',
      value: 'focus_surge',
    },
    runCount: 0,
    iconName: 'Activity',
  },
  {
    id: 'auto-6',
    title: 'Daily Evening Debrief Dispatch',
    description: 'At 21:00 (9:00 PM) daily, compile completed tasks and habits and send a summary push notification with evening reflection questions.',
    enabled: true,
    category: 'execution',
    trigger: {
      type: 'scheduled_time',
      label: 'Every Day at 21:00',
    },
    action: {
      type: 'send_push_notification',
      label: 'Dispatch Evening Review Notification',
      value: 'evening_debrief',
    },
    runCount: 0,
    iconName: 'Clock',
  },
];

export const INITIAL_AUTOMATION_LOGS: AutomationExecutionLog[] = [];

export const INITIAL_GUILDS: GuildSyndicate[] = [
  {
    id: 'guild-1',
    name: 'Apex Strategists',
    tag: 'APEX',
    motto: 'Calculated execution. Asymmetric upside. Unyielding discipline.',
    iconName: 'Crown',
    themeColor: '#f59e0b',
    level: 12,
    totalMembers: 24,
    maxMembers: 30,
    weeklyGuildXp: 84900,
    rank: 1,
    activePerks: [
      '+15% Collective Boss Raid Damage',
      '+10% XP from Trading Discipline',
      'Guild Shield Pooling: 1 Free Revive / wk',
    ],
    activeWorldRaid: {
      id: 'world-boss-1',
      name: 'Leviathan of Chaos',
      title: 'Global World Raid Entity (Tier IV)',
      avatarIcon: 'Skull',
      maxHp: 50000,
      currentHp: 18450,
      communityDamageTotal: 31550,
      expiresInDays: 4,
      rewards: {
        collectiveXpBonus: 5000,
        guildPerk: 'Guild Master Legendary Sigil',
        exclusiveBadge: 'Leviathan Slayer Sovereign',
      },
    },
    members: [
      {
        id: 'mem-1',
        name: 'Alex Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        role: 'Leader',
        weeklyXp: 7420,
        bossDamageContribution: 4200,
        joinedAt: '2026-01-10',
        status: 'focused',
      },
      {
        id: 'mem-2',
        name: 'Marcus Thorne',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        role: 'Officer',
        weeklyXp: 6850,
        bossDamageContribution: 3800,
        joinedAt: '2026-01-14',
        status: 'online',
      },
      {
        id: 'mem-3',
        name: 'Elena Rostova',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        role: 'Officer',
        weeklyXp: 6100,
        bossDamageContribution: 3100,
        joinedAt: '2026-02-01',
        status: 'online',
      },
      {
        id: 'mem-4',
        name: 'Kaito Tanaka',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        role: 'Member',
        weeklyXp: 5400,
        bossDamageContribution: 2900,
        joinedAt: '2026-02-10',
        status: 'idle',
      },
    ],
    isUserMember: true,
  },
  {
    id: 'guild-2',
    name: 'Neural Polymaths',
    tag: 'MIND',
    motto: 'Synthesizing languages, engineering, and deep cognitive flow.',
    iconName: 'Brain',
    themeColor: '#6366f1',
    level: 10,
    totalMembers: 19,
    maxMembers: 30,
    weeklyGuildXp: 72400,
    rank: 2,
    activePerks: [
      '+20% Learning Lab Completion XP',
      '+15% SRS Flashcard Retention Multiplier',
    ],
    activeWorldRaid: {
      id: 'world-boss-1',
      name: 'Leviathan of Chaos',
      title: 'Global World Raid Entity (Tier IV)',
      avatarIcon: 'Skull',
      maxHp: 50000,
      currentHp: 18450,
      communityDamageTotal: 31550,
      expiresInDays: 4,
      rewards: {
        collectiveXpBonus: 5000,
        guildPerk: 'Polymath Neural Crown',
        exclusiveBadge: 'Mind Architect',
      },
    },
    members: [],
    isUserMember: false,
  },
  {
    id: 'guild-3',
    name: 'Titanium Discipline Order',
    tag: 'IRON',
    motto: 'Relentless consistency. No zero days. Iron habits.',
    iconName: 'Shield',
    themeColor: '#10b981',
    level: 9,
    totalMembers: 22,
    maxMembers: 30,
    weeklyGuildXp: 68100,
    rank: 3,
    activePerks: [
      '+25% Habit Streak Bonus XP',
      'Instant Shield Replenish on 14-day Habit milestones',
    ],
    activeWorldRaid: {
      id: 'world-boss-1',
      name: 'Leviathan of Chaos',
      title: 'Global World Raid Entity (Tier IV)',
      avatarIcon: 'Skull',
      maxHp: 50000,
      currentHp: 18450,
      communityDamageTotal: 31550,
      expiresInDays: 4,
      rewards: {
        collectiveXpBonus: 5000,
        guildPerk: 'Titanium Bastion Crest',
        exclusiveBadge: 'Iron Will Paragon',
      },
    },
    members: [],
    isUserMember: false,
  },
];

export const INITIAL_SYNDICATE_LEADERBOARD: SyndicateLeaderboardEntry[] = [
  {
    rank: 1,
    id: 'lead-1',
    name: 'Alex Vance (You)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    guildTag: 'APEX',
    level: 17,
    weeklyXp: 7420,
    bossDamage: 4200,
    habitConsistencyRate: 98,
    tradingSharpe: 2.84,
    trend: 'up',
  },
  {
    rank: 2,
    id: 'lead-2',
    name: 'Seraphina Lin',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    guildTag: 'MIND',
    level: 16,
    weeklyXp: 7150,
    bossDamage: 3950,
    habitConsistencyRate: 96,
    tradingSharpe: 2.45,
    trend: 'up',
  },
  {
    rank: 3,
    id: 'lead-3',
    name: 'Marcus Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    guildTag: 'APEX',
    level: 16,
    weeklyXp: 6850,
    bossDamage: 3800,
    habitConsistencyRate: 94,
    tradingSharpe: 2.61,
    trend: 'same',
  },
  {
    rank: 4,
    id: 'lead-4',
    name: 'Darius Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    guildTag: 'IRON',
    level: 15,
    weeklyXp: 6420,
    bossDamage: 3400,
    habitConsistencyRate: 100,
    tradingSharpe: 2.10,
    trend: 'down',
  },
  {
    rank: 5,
    id: 'lead-5',
    name: 'Elena Rostova',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    guildTag: 'APEX',
    level: 15,
    weeklyXp: 6100,
    bossDamage: 3100,
    habitConsistencyRate: 92,
    tradingSharpe: 2.38,
    trend: 'up',
  },
  {
    rank: 6,
    id: 'lead-6',
    name: 'Kaito Tanaka',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    guildTag: 'MIND',
    level: 14,
    weeklyXp: 5400,
    bossDamage: 2900,
    habitConsistencyRate: 90,
    tradingSharpe: 1.95,
    trend: 'same',
  },
];

export const INITIAL_BIOMETRICS: BiometricReadinessMetric = {
  sleepScore: 89,
  sleepDurationHours: 7.8,
  hrvMilliseconds: 68,
  restingHeartRateBpm: 52,
  recoveryIndex: 92,
  cognitiveReadinessTier: 'Prime Peak',
  focusXpMultiplier: 1.5,
  bossCritMultiplier: 2.0,
  lastSyncedAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  sourceDevice: 'Oura Ring Horizon Gen 3 (Bluetooth Synced)',
};

export const INITIAL_INTEGRATIONS: WebhookIntegrationConfig[] = [
  {
    id: 'int-1',
    name: 'Oura Ring / Apple Health Sync',
    provider: 'oura',
    status: 'connected',
    apiKeyOrToken: 'oura_live_token_77a94d0c921',
    lastEventReceivedAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    eventsCount: 148,
  },
  {
    id: 'int-2',
    name: 'Google Calendar Two-Way Sync',
    provider: 'google_calendar',
    status: 'connected',
    apiKeyOrToken: 'gcal_oauth_refresh_token_active',
    lastEventReceivedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    eventsCount: 92,
  },
  {
    id: 'int-3',
    name: 'Life OS Webhook Dispatcher',
    provider: 'custom_webhook',
    status: 'connected',
    webhookUrl: 'https://api.lifeos.internal/v1/events/webhook',
    apiKeyOrToken: 'sec_key_live_948f10b2c5e',
    lastEventReceivedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    eventsCount: 340,
  },
];
