import {
  SwarmAgent,
  LifeSimulationModel,
  EpochMilestone,
  SovereignVaultArchive,
} from '../types';

export const INITIAL_SWARM_AGENTS: SwarmAgent[] = [
  {
    id: 'agent_sentinel_01',
    name: 'Sentinel-9',
    role: 'Sentinel',
    specialization: 'Real-time Habit Drift & Relapse Prevention',
    status: 'active',
    autonomyLevel: 'autonomous',
    accuracyRate: 99.2,
    actionsExecuted: 42,
    currentObjective: 'Safeguard 24-day Morning Deep Work & Cold Plunge Streaks',
    avatarIcon: 'ShieldAlert',
    lastPingAt: new Date().toISOString(),
    insights: [
      {
        id: 'ins_sentinel_01',
        agentId: 'agent_sentinel_01',
        agentName: 'Sentinel-9',
        title: 'Sleep Dip Predicted Habit Vulnerability',
        description: 'Biometric sleep duration was 6.8h. Automated 1-day Streak Shield armed proactively to protect consistency score.',
        impact: 'high',
        domain: 'discipline',
        suggestedAction: 'Armed 1 Streak Shield & Reduced Morning Habit Target Friction',
        actionPayload: { type: 'replenish_shields', value: 1 },
        status: 'applied',
        confidenceScore: 97,
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      },
      {
        id: 'ins_sentinel_02',
        agentId: 'agent_sentinel_01',
        agentName: 'Sentinel-9',
        title: 'Evening Digital Curfew Warning',
        description: 'Screen usage detected past 22:30. Sentinel recommends triggering auto-lockdown protocol to protect tomorrow HRV.',
        impact: 'medium',
        domain: 'health',
        suggestedAction: 'Initiate 22:45 Night Protocol and dim terminal color balance',
        status: 'pending',
        confidenceScore: 92,
        timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      },
    ],
  },
  {
    id: 'agent_oracle_02',
    name: 'Oracle-Alpha',
    role: 'Oracle',
    specialization: 'Monte Carlo Risk Calibration & Tilt Suppression',
    status: 'active',
    autonomyLevel: 'semi-autonomous',
    accuracyRate: 96.8,
    actionsExecuted: 68,
    currentObjective: 'Maintain Sharpe Ratio > 2.4 across NVDA/BTC/ETH positions',
    avatarIcon: 'TrendingUp',
    lastPingAt: new Date().toISOString(),
    insights: [
      {
        id: 'ins_oracle_01',
        agentId: 'agent_oracle_02',
        agentName: 'Oracle-Alpha',
        title: 'Sector Exposure Concentration Alert',
        description: 'Tech long exposure represents 34% of open risk budget. Trailing stop adjustments recommended on NVDA long.',
        impact: 'critical',
        domain: 'trading',
        suggestedAction: 'Tighten trailing stop on NVDA to $128.50 to lock in +$1,850 profit',
        actionPayload: { type: 'lock_risk', value: 'NVDA_128.50' },
        status: 'pending',
        confidenceScore: 95,
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      },
      {
        id: 'ins_oracle_02',
        agentId: 'agent_oracle_02',
        agentName: 'Oracle-Alpha',
        title: 'High Expectancy Entry Setup Detected',
        description: 'ETH/USDT 4H Bullish Order Block retest confirmed with positive CVD divergence (Win Rate Expectancy: 74%).',
        impact: 'high',
        domain: 'trading',
        suggestedAction: 'Log trade thesis to Trading Terminal with strict 1.5% risk cap',
        status: 'pending',
        confidenceScore: 89,
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
    ],
  },
  {
    id: 'agent_archivist_03',
    name: 'Archivist-Prime',
    role: 'Archivist',
    specialization: 'Active Recall Synthesis & Cross-Discipline Retention',
    status: 'analyzing',
    autonomyLevel: 'autonomous',
    accuracyRate: 98.6,
    actionsExecuted: 114,
    currentObjective: 'Compile Distributed Systems Consensus deck for 20:00 SRS session',
    avatarIcon: 'Brain',
    lastPingAt: new Date().toISOString(),
    insights: [
      {
        id: 'ins_archivist_01',
        agentId: 'agent_archivist_03',
        agentName: 'Archivist-Prime',
        title: 'Spaced Repetition Deck Generated',
        description: 'Extracted 12 active recall prompts from "Distributed Consensus & Raft Protocol" study notes.',
        impact: 'medium',
        domain: 'learning',
        suggestedAction: 'Auto-schedule 15-minute flashcard review in Learning Hub',
        actionPayload: { type: 'create_srs_deck', value: 'Raft_Consensus_12' },
        status: 'applied',
        confidenceScore: 99,
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      },
    ],
  },
  {
    id: 'agent_tactician_04',
    name: 'Tactician-Flow',
    role: 'Tactician',
    specialization: 'Dynamic Schedule Allocation & High-HRV Slot Matching',
    status: 'active',
    autonomyLevel: 'autonomous',
    accuracyRate: 97.9,
    actionsExecuted: 89,
    currentObjective: 'Lock 09:00 - 11:30 for High-Impact System Architecture (HRV at 72ms peak)',
    avatarIcon: 'Calendar',
    lastPingAt: new Date().toISOString(),
    insights: [
      {
        id: 'ins_tactician_01',
        agentId: 'agent_tactician_04',
        agentName: 'Tactician-Flow',
        title: 'Cognitive Peak Slot Rescheduled',
        description: 'Wearables confirmed peak REM recovery. Moved low-leverage email triage to 16:00 to reserve morning for coding.',
        impact: 'high',
        domain: 'time',
        suggestedAction: 'Rescheduled 2 non-critical events on Planner Calendar',
        actionPayload: { type: 'reschedule_calendar', value: 'Morning_Deep_Work_Block' },
        status: 'applied',
        confidenceScore: 98,
        timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      },
    ],
  },
  {
    id: 'agent_strategist_05',
    name: 'Strategist-Epoch',
    role: 'Strategist',
    specialization: 'Multi-Epoch Trajectory & Quantum Scenario Convergence',
    status: 'standby',
    autonomyLevel: 'advisory',
    accuracyRate: 95.5,
    actionsExecuted: 23,
    currentObjective: 'Project 2026 Q3 Goal Velocity vs Monte Carlo Baseline',
    avatarIcon: 'Compass',
    lastPingAt: new Date().toISOString(),
    insights: [
      {
        id: 'ins_strategist_01',
        agentId: 'agent_strategist_05',
        agentName: 'Strategist-Epoch',
        title: 'Multi-Year Compounding Trajectory on Track',
        description: 'Output momentum is tracking +18% ahead of 5-year financial sovereignty and mastery forecast.',
        impact: 'medium',
        domain: 'discipline',
        suggestedAction: 'Run updated 5-Year Quantum Scenario Simulation in Simulation Lab',
        status: 'pending',
        confidenceScore: 94,
        timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
      },
    ],
  },
];

export const INITIAL_SIMULATION_MODELS: LifeSimulationModel[] = [
  {
    id: 'sim_5yr_default',
    name: '5-Year Sovereign Mastery & Wealth Acceleration',
    description: 'High-discipline compounding model balancing 4.5h daily deep work, $2,500/mo index compounding, and 92% habit discipline.',
    timeHorizonYears: 5,
    baseParameters: {
      habitConsistencyRate: 92,
      dailyDeepWorkHours: 4.5,
      monthlySavingsRate: 2500,
      investmentAnnualReturn: 11.5,
      dailyLearningHours: 1.5,
      exerciseDaysPerWeek: 5,
    },
    trajectories: {
      p10: [
        { year: 2026, month: 1, wealthScore: 120000, masteryScore: 2400, vitalityScore: 82, compositeLifeScore: 78 },
        { year: 2027, month: 1, wealthScore: 154000, masteryScore: 3100, vitalityScore: 79, compositeLifeScore: 80 },
        { year: 2028, month: 1, wealthScore: 195000, masteryScore: 3800, vitalityScore: 76, compositeLifeScore: 81 },
        { year: 2029, month: 1, wealthScore: 245000, masteryScore: 4600, vitalityScore: 74, compositeLifeScore: 83 },
        { year: 2030, month: 1, wealthScore: 310000, masteryScore: 5400, vitalityScore: 72, compositeLifeScore: 84 },
        { year: 2031, month: 1, wealthScore: 390000, masteryScore: 6200, vitalityScore: 70, compositeLifeScore: 85 },
      ],
      p50: [
        { year: 2026, month: 1, wealthScore: 120000, masteryScore: 2400, vitalityScore: 88, compositeLifeScore: 85 },
        { year: 2027, month: 1, wealthScore: 172000, masteryScore: 3800, vitalityScore: 89, compositeLifeScore: 88 },
        { year: 2028, month: 1, wealthScore: 245000, masteryScore: 5600, vitalityScore: 90, compositeLifeScore: 91 },
        { year: 2029, month: 1, wealthScore: 348000, masteryScore: 7800, vitalityScore: 91, compositeLifeScore: 93 },
        { year: 2030, month: 1, wealthScore: 485000, masteryScore: 10400, vitalityScore: 92, compositeLifeScore: 95 },
        { year: 2031, month: 1, wealthScore: 660000, masteryScore: 13500, vitalityScore: 93, compositeLifeScore: 97 },
      ],
      p90: [
        { year: 2026, month: 1, wealthScore: 120000, masteryScore: 2400, vitalityScore: 92, compositeLifeScore: 89 },
        { year: 2027, month: 1, wealthScore: 198000, masteryScore: 4600, vitalityScore: 94, compositeLifeScore: 92 },
        { year: 2028, month: 1, wealthScore: 320000, masteryScore: 7900, vitalityScore: 95, compositeLifeScore: 95 },
        { year: 2029, month: 1, wealthScore: 510000, masteryScore: 12400, vitalityScore: 96, compositeLifeScore: 97 },
        { year: 2030, month: 1, wealthScore: 790000, masteryScore: 18200, vitalityScore: 97, compositeLifeScore: 99 },
        { year: 2031, month: 1, wealthScore: 1180000, masteryScore: 25600, vitalityScore: 98, compositeLifeScore: 100 },
      ],
    },
    projectedOutcomes: {
      netWorth: 660000,
      skillMasteryPoints: 13500,
      vitalityBiologicalAgeOffset: -4.2,
      lifeSynergyIndex: 94,
    },
    recommendations: [
      'Maintaining habit consistency at >= 90% protects your baseline from drifting toward the p10 lower boundary.',
      'Increasing monthly DCA savings by $400 shifts the median 5-year wealth outcome by +$68,000.',
      'Sustaining 5 gym sessions weekly maintains biological age reduction at -4.2 years below chronological age.',
      'Daily 1.5h active recall deepens long-term retention by 3.8x compared to passive reading.',
    ],
  },
];

export const INITIAL_EPOCH_MILESTONES: EpochMilestone[] = [
  {
    id: 'epoch_01',
    epochName: 'Epoch I: Foundation & Relentless Execution (2024 - 2025)',
    title: 'Architected & Shipped Distributed Microservices Engine',
    category: 'mastery',
    achievedAt: '2025-11-14',
    description: 'Constructed event-driven microservices architecture handling 50k concurrent requests with 99.99% uptime.',
    significanceRank: 'Tier S',
    proofArtifact: 'GitHub Release Tag v2.4.0 & Architecture RFC',
    status: 'completed',
  },
  {
    id: 'epoch_02',
    epochName: 'Epoch I: Foundation & Relentless Execution (2024 - 2025)',
    title: 'Achieved 365-Day Unbroken Habit Discipline Matrix',
    category: 'vitality',
    achievedAt: '2025-12-31',
    description: 'Completed 365 consecutive days of morning deep work, physical training, and zero skipped core routines.',
    significanceRank: 'Tier S',
    proofArtifact: 'Life OS Certified 365-Streak cryptographic badge',
    status: 'completed',
  },
  {
    id: 'epoch_03',
    epochName: 'Epoch II: Sovereign Mastery & Scaled Alpha (2026 - 2027)',
    title: 'Defeat Tier IV World Raid & Guild Syndicate Grand Champion',
    category: 'breakthrough',
    achievedAt: '2026-08-17',
    description: 'Lead Sovereign Guild to top #3 global ranking and inflict over 100,000 damage on the Leviathan Raid Boss.',
    significanceRank: 'Tier S',
    proofArtifact: 'Syndicate Hall of Fame Ledger #3',
    status: 'in_progress',
  },
  {
    id: 'epoch_04',
    epochName: 'Epoch II: Sovereign Mastery & Scaled Alpha (2026 - 2027)',
    title: 'Attain Japanese N2 Business Fluency & Technical Translation',
    category: 'mastery',
    achievedAt: '2026-12-15',
    description: 'Complete all 2,136 Joyo Kanji and pass JLPT N2 with 90%+ reading comprehension score.',
    significanceRank: 'Tier A',
    proofArtifact: 'JLPT N2 Official Certificate Token',
    status: 'in_progress',
  },
  {
    id: 'epoch_05',
    epochName: 'Epoch III: Self-Actualization & Sovereign Legacy (2028 - 2030)',
    title: 'Establish Decentralized Sovereign Autonomous Research Lab',
    category: 'financial',
    achievedAt: '2028-06-30',
    description: 'Attain complete financial independence and bootstrap an independent software & AI research collective.',
    significanceRank: 'Tier S',
    proofArtifact: 'Sovereign Foundation Charter & Treasury Endowment',
    status: 'target',
  },
];

export const INITIAL_VAULT_ARCHIVES: SovereignVaultArchive[] = [
  {
    id: 'vault_arch_01',
    backupVersion: 'v10.0-SOVEREIGN-MASTER',
    createdAt: new Date().toISOString(),
    totalRecords: 1420,
    dataSizeKb: 348,
    encryptionAlgorithm: 'AES-256-GCM Zero-Knowledge Client Cipher',
    checksum: 'e7b8c9d2f4a180329b8c9d0124f5a3b2c1e8',
    offlineReady: true,
    exportFormat: 'json',
  },
  {
    id: 'vault_arch_02',
    backupVersion: 'v9.4-SYNDICATE-STABLE',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    totalRecords: 1280,
    dataSizeKb: 295,
    encryptionAlgorithm: 'AES-256-GCM Zero-Knowledge Client Cipher',
    checksum: 'a1b2c3d4e5f67890123456789abcdef01234',
    offlineReady: true,
    exportFormat: 'standalone_html',
  },
];
