import {
  BossBattle,
  SkillPerkNode,
  CrossDomainLifeRadarData,
  HistoricalXpTrendPoint,
  DomainDistributionPoint,
  FlowHourHeatmapPoint,
  SystemSnapshotMetadata,
} from '../types';

export const INITIAL_BOSS_BATTLES: BossBattle[] = [
  {
    id: 'boss-1',
    name: 'The Procrastination Behemoth',
    subtitle: 'Lord of Tomorrow & Architect of Delay',
    lore: 'A hulking creature born of deferred obligations and endless distraction loops. It feeds on uncompleted high-priority tasks and broken morning routines. Channel deep focus to shatter its inertia armor.',
    avatarIcon: 'Skull',
    themeColor: 'amber',
    currentHp: 1850,
    maxHp: 5000,
    difficulty: 'Standard',
    deadlineDays: 5,
    startDate: '2026-08-15T00:00:00Z',
    endDate: '2026-08-22T23:59:59Z',
    defeated: false,
    rewards: {
      xp: 1250,
      badgeTitle: 'Behemoth Slayer',
      perkPoints: 3,
      lootDescription: 'Mythic Chrono-Shard (+10% Task XP permanent bonus) & 3 Skill Perk Points',
    },
    activeModifiers: [
      {
        title: 'High-Priority Vulnerability',
        effect: 'High-priority tasks deal 2.0x Critical Damage (100 DMG per task).',
        damageMultiplier: 2.0,
        category: 'task',
      },
      {
        title: 'Morning Strike Weakness',
        effect: 'Tasks completed before 11:00 AM deal +50 bonus damage.',
        damageMultiplier: 1.5,
        category: 'task',
      },
      {
        title: 'Consistency Pressure',
        effect: 'Checking daily habits deals 40 passive siege damage per check.',
        damageMultiplier: 1.2,
        category: 'habit',
      },
    ],
    damageLog: [
      {
        id: 'dmg-1',
        timestamp: '2026-08-17T09:45:00Z',
        damage: 150,
        reason: 'Completed High-Priority Task: "Review System Architecture PR"',
        category: 'task',
      },
      {
        id: 'dmg-2',
        timestamp: '2026-08-17T07:15:00Z',
        damage: 60,
        reason: 'Checked Morning Habit: "Deep Work / Code"',
        category: 'habit',
      },
      {
        id: 'dmg-3',
        timestamp: '2026-08-16T18:30:00Z',
        damage: 200,
        reason: 'Mastered 10 SRS Vocabulary Cards (German Unit 2)',
        category: 'language',
      },
      {
        id: 'dmg-4',
        timestamp: '2026-08-16T14:20:00Z',
        damage: 180,
        reason: 'Completed React Performance Lab in Course Engine',
        category: 'course',
      },
      {
        id: 'dmg-5',
        timestamp: '2026-08-15T16:45:00Z',
        damage: 120,
        reason: 'Logged Disciplined Trade on BTC/USDT (+2.4R win)',
        category: 'trading',
      },
    ],
  },
  {
    id: 'boss-2',
    name: 'Market Chaos Leviathan',
    subtitle: 'Titan of Emotional Drawdown & Volatility',
    lore: 'An aquatic titan dwelling in erratic market chop and revenge-trading spirals. It strikes when risk management breaks. Defeat it by adhering strictly to your trading rules and position sizing.',
    avatarIcon: 'Flame',
    themeColor: 'red',
    currentHp: 6500,
    maxHp: 7500,
    difficulty: 'Heroic',
    deadlineDays: 9,
    startDate: '2026-08-14T00:00:00Z',
    endDate: '2026-08-25T23:59:59Z',
    defeated: false,
    rewards: {
      xp: 2000,
      badgeTitle: 'Leviathan Subduer',
      perkPoints: 4,
      lootDescription: 'Aegis of Capital (+15% Trading XP & Zero-Tilt Aura) & 4 Perk Points',
    },
    activeModifiers: [
      {
        title: 'Risk Discipline Cleave',
        effect: 'Trades logged with valid Stop Loss & strict sizing deal 250 DMG.',
        damageMultiplier: 2.5,
        category: 'trading',
      },
      {
        title: 'Habit Shield',
        effect: 'Daily Meditation & Journaling habits inflict 75 direct bleed damage.',
        damageMultiplier: 1.5,
        category: 'habit',
      },
    ],
    damageLog: [
      {
        id: 'dmg-l1',
        timestamp: '2026-08-17T08:30:00Z',
        damage: 250,
        reason: 'Logged Disciplined Breakout Trade with 1.8% Stop Loss',
        category: 'trading',
      },
      {
        id: 'dmg-l2',
        timestamp: '2026-08-16T09:00:00Z',
        damage: 150,
        reason: 'Completed Morning Market Prep & Watchlist Audit',
        category: 'task',
      },
    ],
  },
  {
    id: 'boss-3',
    name: 'The Polyglot Titan',
    subtitle: 'Guardian of the Tower of Babel',
    lore: 'A towering colossus wrapped in ancient glyphs and lexicons. It tests conversational fluency and daily vocabulary retention.',
    avatarIcon: 'Globe',
    themeColor: 'blue',
    currentHp: 0,
    maxHp: 4000,
    difficulty: 'Standard',
    deadlineDays: 0,
    startDate: '2026-08-01T00:00:00Z',
    endDate: '2026-08-10T23:59:59Z',
    defeated: true,
    defeatedAt: '2026-08-09T18:20:00Z',
    rewards: {
      xp: 1500,
      badgeTitle: 'Babel Conqueror',
      perkPoints: 3,
      lootDescription: 'Linguistic Resonance Matrix (+20% SRS Mastery Speed)',
    },
    activeModifiers: [
      {
        title: 'Dialogue Surge',
        effect: 'Interactive conversational sessions deal 300 DMG.',
        damageMultiplier: 2.0,
        category: 'language',
      },
    ],
    damageLog: [
      {
        id: 'dmg-p1',
        timestamp: '2026-08-09T18:20:00Z',
        damage: 400,
        reason: 'Final Blow: Completed German B1 Dialogue Mastery Session',
        category: 'language',
      },
    ],
  },
];

export const INITIAL_SKILL_PERK_NODES: SkillPerkNode[] = [
  // --- EXECUTION DOMAIN (Emerald) ---
  {
    id: 'perk-exec-1',
    title: 'Flow State Surge',
    description: 'Increases XP gained from completing High-Priority and Engineering tasks by +15%.',
    domain: 'execution',
    tier: 1,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-02T10:00:00Z',
    iconName: 'Zap',
    passiveEffect: '+15% High-Priority Task XP',
    bonusMultiplier: 1.15,
    dependencies: [],
  },
  {
    id: 'perk-exec-2',
    title: 'Eisenhower Precision',
    description: 'Completing all scheduled daily tasks before 6:00 PM grants a +50 XP bonus burst.',
    domain: 'execution',
    tier: 2,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-10T14:30:00Z',
    iconName: 'Target',
    passiveEffect: '+50 XP Daily Schedule Clear Bonus',
    bonusMultiplier: 1.2,
    dependencies: ['perk-exec-1'],
  },
  {
    id: 'perk-exec-3',
    title: 'Boss Raid Siege Engine',
    description: 'All tasks completed deal +35% increased damage to active Boss Battles.',
    domain: 'execution',
    tier: 3,
    costPoints: 2,
    unlocked: false,
    iconName: 'Sword',
    passiveEffect: '+35% Boss Raid Task Damage',
    bonusMultiplier: 1.35,
    dependencies: ['perk-exec-2'],
  },
  {
    id: 'perk-exec-4',
    title: 'Omni-Executor Capstone',
    description: 'Transcendent execution speed: Completing tasks triggers an instant 10% cooldown refund on Streak Shields and adds +100 bonus Boss damage.',
    domain: 'execution',
    tier: 4,
    costPoints: 3,
    unlocked: false,
    iconName: 'Crown',
    passiveEffect: 'Passive Shield Cooldown Refund & Massive Boss Blast',
    bonusMultiplier: 1.5,
    dependencies: ['perk-exec-3'],
  },

  // --- CONSISTENCY DOMAIN (Orange) ---
  {
    id: 'perk-const-1',
    title: 'Streak Armor',
    description: 'Reduces Streak Shield recharge duration by 24 hours. Daily habit XP increased by +10%.',
    domain: 'consistency',
    tier: 1,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-05T08:00:00Z',
    iconName: 'Shield',
    passiveEffect: '+10% Habit XP & Faster Shield Recovery',
    bonusMultiplier: 1.1,
    dependencies: [],
  },
  {
    id: 'perk-const-2',
    title: 'Habit Synergy Matrix',
    description: 'Checking 4 or more habits in a single day multiplies your daily streak XP bonus by 1.25x.',
    domain: 'consistency',
    tier: 2,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-12T19:00:00Z',
    iconName: 'Flame',
    passiveEffect: '1.25x Multiplier on 4+ Daily Habits',
    bonusMultiplier: 1.25,
    dependencies: ['perk-const-1'],
  },
  {
    id: 'perk-const-3',
    title: 'Momentum Fortress',
    description: 'Reaching a 14-day streak grants an auto-replenishing emergency shield once per month.',
    domain: 'consistency',
    tier: 3,
    costPoints: 2,
    unlocked: false,
    iconName: 'Lock',
    passiveEffect: 'Emergency Auto-Shield on 14+ Streak',
    bonusMultiplier: 1.3,
    dependencies: ['perk-const-2'],
  },
  {
    id: 'perk-const-4',
    title: 'Titanium Discipline Capstone',
    description: 'The pinnacle of routine. Habit completion rewards are permanently doubled and passive boss siege damage is increased by +100%.',
    domain: 'consistency',
    tier: 4,
    costPoints: 3,
    unlocked: false,
    iconName: 'Sparkles',
    passiveEffect: '2.0x Habit XP & Double Boss Siege DMG',
    bonusMultiplier: 2.0,
    dependencies: ['perk-const-3'],
  },

  // --- KNOWLEDGE DOMAIN (Blue/Indigo) ---
  {
    id: 'perk-know-1',
    title: 'Cognitive Velocity',
    description: 'Reading course theory and completing interactive coding labs awards +20% bonus XP.',
    domain: 'knowledge',
    tier: 1,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-08T16:00:00Z',
    iconName: 'BookOpen',
    passiveEffect: '+20% Course & Lab XP',
    bonusMultiplier: 1.2,
    dependencies: [],
  },
  {
    id: 'perk-know-2',
    title: 'SRS Neural Retention',
    description: 'Spaced repetition flashcard reviews yield double XP on 4+ streak correct answers.',
    domain: 'knowledge',
    tier: 2,
    costPoints: 1,
    unlocked: false,
    iconName: 'Brain',
    passiveEffect: '2.0x XP on 4+ Flashcard Streak',
    bonusMultiplier: 1.35,
    dependencies: ['perk-know-1'],
  },
  {
    id: 'perk-know-3',
    title: 'Polymath Synthesis',
    description: 'Completing learning modules unlocks AI cross-domain correlation tips that increase daily planning efficiency.',
    domain: 'knowledge',
    tier: 3,
    costPoints: 2,
    unlocked: false,
    iconName: 'Layers',
    passiveEffect: 'Unlock Advanced AI Syllabus Synthesizer',
    bonusMultiplier: 1.4,
    dependencies: ['perk-know-2'],
  },
  {
    id: 'perk-know-4',
    title: 'Ascendant Intellect Capstone',
    description: 'Complete mastery of learning pipelines. All course certificates yield +500 XP and grant an instant +1 Skill Perk Point.',
    domain: 'knowledge',
    tier: 4,
    costPoints: 3,
    unlocked: false,
    iconName: 'GraduationCap',
    passiveEffect: '+500 XP & +1 Perk Point per Certificate',
    bonusMultiplier: 1.75,
    dependencies: ['perk-know-3'],
  },

  // --- STRATEGY & MARKET DOMAIN (Purple/Amber) ---
  {
    id: 'perk-strat-1',
    title: 'Risk Disciplinarian',
    description: 'Logging every trade with defined Stop Loss and Take Profit levels earns a +25 XP Journaling reward.',
    domain: 'strategy',
    tier: 1,
    costPoints: 1,
    unlocked: true,
    unlockedAt: '2026-08-04T12:00:00Z',
    iconName: 'ShieldCheck',
    passiveEffect: '+25 XP for Disciplined Trade Logging',
    bonusMultiplier: 1.15,
    dependencies: [],
  },
  {
    id: 'perk-strat-2',
    title: 'R-Multiple Mastery',
    description: 'Trades achieving > 2.0R reward-to-risk ratio inflict +150 critical damage to active Boss Battles.',
    domain: 'strategy',
    tier: 2,
    costPoints: 1,
    unlocked: false,
    iconName: 'TrendingUp',
    passiveEffect: '+150 Boss DMG on >2.0R Trades',
    bonusMultiplier: 1.3,
    dependencies: ['perk-strat-1'],
  },
  {
    id: 'perk-strat-3',
    title: 'Emotional Anti-Fragility',
    description: 'Neutralizes tilt penalties: Logging a loss with a calm emotional state reflection prevents streak multiplier deduction.',
    domain: 'strategy',
    tier: 3,
    costPoints: 2,
    unlocked: false,
    iconName: 'HeartHandshake',
    passiveEffect: 'Zero-Tilt Loss Buffer & Calm Reflection Bonus',
    bonusMultiplier: 1.4,
    dependencies: ['perk-strat-2'],
  },
  {
    id: 'perk-strat-4',
    title: 'Grand Strategist Capstone',
    description: 'Mastery over capital, strategy, and risk. Unlocks the AI Strategic Arbitrage Simulator and adds +50% XP to all financial milestones.',
    domain: 'strategy',
    tier: 4,
    costPoints: 3,
    unlocked: false,
    iconName: 'Compass',
    passiveEffect: '+50% Financial Goal XP & Strategic AI Hub',
    bonusMultiplier: 1.8,
    dependencies: ['perk-strat-3'],
  },
];

export const INITIAL_CROSS_DOMAIN_RADAR: CrossDomainLifeRadarData = {
  overallSynergyScore: 88,
  synergyTier: 'Optimal',
  metrics: [
    {
      pillar: 'Execution Power',
      domainKey: 'execution',
      score: 92,
      benchmark: 75,
      grade: 'S',
      summary: 'Outstanding task velocity and high-priority closure rate in morning peak hours.',
      primaryMetricLabel: 'Task Completion Rate',
      primaryMetricValue: '94.2%',
      submetrics: [
        { label: 'High Priority Cleared', value: '18 / 19', status: 'optimal' },
        { label: 'Avg Closure Time', value: '42 mins', status: 'optimal' },
        { label: 'Time-block Adherence', value: '88%', status: 'good' },
      ],
    },
    {
      pillar: 'Habit Consistency',
      domainKey: 'consistency',
      score: 86,
      benchmark: 70,
      grade: 'A',
      summary: 'Solid 24-day active streak with balanced physical health and deep coding routines.',
      primaryMetricLabel: 'Active Streak',
      primaryMetricValue: '24 Days',
      submetrics: [
        { label: '60-Day Consistency', value: '89.4%', status: 'optimal' },
        { label: 'Morning Routine Pass', value: '92%', status: 'optimal' },
        { label: 'Evening Wind-down', value: '78%', status: 'good' },
      ],
    },
    {
      pillar: 'Strategic & Vision',
      domainKey: 'strategy',
      score: 84,
      benchmark: 65,
      grade: 'A',
      summary: 'Q3 roadmap milestones on schedule; 5-year career pillar tracking at 76%.',
      primaryMetricLabel: 'Milestones on Track',
      primaryMetricValue: '12 / 14',
      submetrics: [
        { label: 'Quarterly OKR Velocity', value: '82%', status: 'optimal' },
        { label: '5-Year Alignment', value: '85%', status: 'good' },
        { label: 'Weekly Review Rate', value: '100%', status: 'optimal' },
      ],
    },
    {
      pillar: 'Intellectual Growth',
      domainKey: 'intellect',
      score: 90,
      benchmark: 70,
      grade: 'S',
      summary: 'Advanced progress through TypeScript Architecture and React Performance labs.',
      primaryMetricLabel: 'Courses Completed',
      primaryMetricValue: '3 / 4 Courses',
      submetrics: [
        { label: 'Interactive Lab Score', value: '98%', status: 'optimal' },
        { label: 'Quiz Accuracy', value: '94%', status: 'optimal' },
        { label: 'Weekly Study Time', value: '6.4 hrs', status: 'optimal' },
      ],
    },
    {
      pillar: 'Linguistic Mastery',
      domainKey: 'linguistics',
      score: 80,
      benchmark: 60,
      grade: 'B',
      summary: 'German B1 vocabulary retention at 86%; dialogue roleplays completed regularly.',
      primaryMetricLabel: 'Mastered Vocab',
      primaryMetricValue: '142 Words',
      submetrics: [
        { label: 'SRS Retention Rate', value: '87.5%', status: 'optimal' },
        { label: 'Dialogue Sessions', value: '8 logged', status: 'good' },
        { label: 'Daily Practice Streak', value: '14 days', status: 'good' },
      ],
    },
    {
      pillar: 'Market & Risk Discipline',
      domainKey: 'trading',
      score: 88,
      benchmark: 60,
      grade: 'A',
      summary: 'Positive expectancy with 62.5% win rate, strict stop-losses, and low emotional tilt.',
      primaryMetricLabel: 'Profit Factor',
      primaryMetricValue: '2.45 PF',
      submetrics: [
        { label: 'Win Rate', value: '62.5%', status: 'optimal' },
        { label: 'Avg R-Multiple', value: '+2.1R', status: 'optimal' },
        { label: 'Rule Adherence', value: '96%', status: 'optimal' },
      ],
    },
  ],
  insights: [
    {
      id: 'ins-1',
      title: 'Habit Consistency Drives Trading Calmness',
      description: 'Days where morning meditation and physical exercise are checked show a +32% reduction in impulse trading entries and +0.8 higher average R-multiple.',
      impact: 'positive',
      actionableStep: 'Maintain the 07:00 AM meditation routine on high-volatility market days (Wednesdays & FOMC days).',
    },
    {
      id: 'ins-2',
      title: 'Peak Cognitive Velocity Window',
      description: 'Your highest task completion and code lab accuracy occurs between 08:30 AM and 11:45 AM, contributing 64% of all daily Boss Raid damage.',
      impact: 'positive',
      actionableStep: 'Block 09:00–11:30 AM exclusively for Tier-1 engineering tasks and avoid context-switching meetings.',
    },
    {
      id: 'ins-3',
      title: 'Evening Linguistics Retention Opportunity',
      description: 'German SRS flashcard retention drops from 91% to 74% when practiced after 10:00 PM due to cognitive fatigue.',
      impact: 'warning',
      actionableStep: 'Shift vocab reviews to a 15-minute afternoon buffer at 4:30 PM for optimal long-term memory consolidation.',
    },
  ],
};

export const INITIAL_HISTORICAL_XP_TREND: HistoricalXpTrendPoint[] = [
  { date: '2026-08-03', displayDate: 'Aug 03', xp: 420, tasksCompleted: 4, habitsChecked: 5, studyMinutes: 45, tradingTrades: 2 },
  { date: '2026-08-04', displayDate: 'Aug 04', xp: 510, tasksCompleted: 5, habitsChecked: 6, studyMinutes: 60, tradingTrades: 1 },
  { date: '2026-08-05', displayDate: 'Aug 05', xp: 380, tasksCompleted: 3, habitsChecked: 5, studyMinutes: 30, tradingTrades: 3 },
  { date: '2026-08-06', displayDate: 'Aug 06', xp: 620, tasksCompleted: 6, habitsChecked: 6, studyMinutes: 90, tradingTrades: 2 },
  { date: '2026-08-07', displayDate: 'Aug 07', xp: 490, tasksCompleted: 5, habitsChecked: 5, studyMinutes: 45, tradingTrades: 0 },
  { date: '2026-08-08', displayDate: 'Aug 08', xp: 580, tasksCompleted: 5, habitsChecked: 6, studyMinutes: 75, tradingTrades: 1 },
  { date: '2026-08-09', displayDate: 'Aug 09', xp: 670, tasksCompleted: 6, habitsChecked: 6, studyMinutes: 110, tradingTrades: 2 },
  { date: '2026-08-10', displayDate: 'Aug 10', xp: 430, tasksCompleted: 4, habitsChecked: 5, studyMinutes: 40, tradingTrades: 1 },
  { date: '2026-08-11', displayDate: 'Aug 11', xp: 550, tasksCompleted: 5, habitsChecked: 6, studyMinutes: 65, tradingTrades: 2 },
  { date: '2026-08-12', displayDate: 'Aug 12', xp: 710, tasksCompleted: 7, habitsChecked: 6, studyMinutes: 95, tradingTrades: 3 },
  { date: '2026-08-13', displayDate: 'Aug 13', xp: 480, tasksCompleted: 4, habitsChecked: 5, studyMinutes: 50, tradingTrades: 1 },
  { date: '2026-08-14', displayDate: 'Aug 14', xp: 640, tasksCompleted: 6, habitsChecked: 6, studyMinutes: 80, tradingTrades: 2 },
  { date: '2026-08-15', displayDate: 'Aug 15', xp: 590, tasksCompleted: 5, habitsChecked: 6, studyMinutes: 70, tradingTrades: 2 },
  { date: '2026-08-16', displayDate: 'Aug 16', xp: 750, tasksCompleted: 7, habitsChecked: 6, studyMinutes: 120, tradingTrades: 1 },
  { date: '2026-08-17', displayDate: 'Aug 17', xp: 820, tasksCompleted: 8, habitsChecked: 6, studyMinutes: 85, tradingTrades: 3 },
];

export const INITIAL_DOMAIN_DISTRIBUTION: DomainDistributionPoint[] = [
  { name: 'Engineering & Tasks', xp: 2840, percentage: 38, color: '#10b981' },
  { name: 'Habits & Routine', xp: 1720, percentage: 23, color: '#f59e0b' },
  { name: 'Learning & Code Labs', xp: 1450, percentage: 20, color: '#6366f1' },
  { name: 'Trading & Markets', xp: 860, percentage: 12, color: '#ec4899' },
  { name: 'Languages & Vocab', xp: 550, percentage: 7, color: '#06b6d4' },
];

export const INITIAL_FLOW_HEATMAP: FlowHourHeatmapPoint[] = [
  { hour: 6, label: '06:00', focusUnits: 15, intensity: 'low' },
  { hour: 7, label: '07:00', focusUnits: 35, intensity: 'medium' },
  { hour: 8, label: '08:00', focusUnits: 70, intensity: 'high' },
  { hour: 9, label: '09:00', focusUnits: 95, intensity: 'peak' },
  { hour: 10, label: '10:00', focusUnits: 90, intensity: 'peak' },
  { hour: 11, label: '11:00', focusUnits: 85, intensity: 'peak' },
  { hour: 12, label: '12:00', focusUnits: 40, intensity: 'medium' },
  { hour: 13, label: '13:00', focusUnits: 30, intensity: 'low' },
  { hour: 14, label: '14:00', focusUnits: 75, intensity: 'high' },
  { hour: 15, label: '15:00', focusUnits: 80, intensity: 'high' },
  { hour: 16, label: '16:00', focusUnits: 65, intensity: 'medium' },
  { hour: 17, label: '17:00', focusUnits: 50, intensity: 'medium' },
  { hour: 18, label: '18:00', focusUnits: 35, intensity: 'low' },
  { hour: 19, label: '19:00', focusUnits: 45, intensity: 'medium' },
  { hour: 20, label: '20:00', focusUnits: 55, intensity: 'medium' },
  { hour: 21, label: '21:00', focusUnits: 20, intensity: 'low' },
  { hour: 22, label: '22:00', focusUnits: 10, intensity: 'none' },
];

export const INITIAL_SYSTEM_SNAPSHOT: SystemSnapshotMetadata = {
  exportedAt: new Date().toISOString(),
  version: '1.0.0-phase8',
  totalXp: 0,
  level: 1,
  tasksCount: 6,
  habitsCount: 6,
  goalsCount: 3,
  coursesCount: 3,
  tradesCount: 0,
};
